import type { ReactNode } from "react";
import QuizBlock from "../Quiz/QuizBlock";
import VideoBlock from "../Video/VideoBlock";
import ConceptCardStack from "./ConceptCardStack";
import { DeleteBlockButton, EditPencilButton, promptForDeleteConfirmation, promptForText } from "./CourseEditControls";
import ProjectBlock from "./ProjectBlock";
import type {
  ContentBlock,
  ProjectSubmissionStatusHandler,
  QuizProgressStatusHandler,
  QuizSubmissionStatusHandler,
  SourceRecord,
} from "./contentViewTypes";
import type { CourseSourceIndex } from "./sourceCitationUtils";
import { sourceCitationNumber } from "./sourceCitationUtils";

type EditableContentBlockProps = {
  block: ContentBlock;
  blockIndex: number;
  courseKey: string;
  sources: SourceRecord[];
  courseSourceIndex: CourseSourceIndex;
  sectionId: string;
  isEditMode: boolean;
  onBlockChange?: (sectionId: string, blockIndex: number, block: ContentBlock) => void;
  onBlockDelete?: (sectionId: string, blockIndex: number) => void;
  onCitationClick?: (citationIndex: number) => void;
  onMissingCitationClick?: () => void;
  onQuizSubmissionChange: QuizSubmissionStatusHandler;
  onQuizProgressChange: QuizProgressStatusHandler;
  onProjectSubmissionChange: ProjectSubmissionStatusHandler;
};

function getSourcesByIds(sourceIds: string[] | undefined, sources: SourceRecord[]) {
  if (!Array.isArray(sourceIds) || sourceIds.length === 0) {
    return [];
  }

  const sourceMap = new Map(sources.map((source) => [source.id, source]));
  return sourceIds
    .map((sourceId) => sourceMap.get(sourceId))
    .filter((source): source is SourceRecord => Boolean(source));
}

function getVideoClip(item: ContentBlock) {
  const clip = item.clip ?? {};
  const startSeconds = clip.startSeconds ?? clip.start ?? item.startSeconds ?? item.start_seconds;
  const endSeconds = clip.endSeconds ?? clip.end ?? item.endSeconds ?? item.end_seconds;

  if (startSeconds === undefined && endSeconds === undefined) {
    return undefined;
  }

  return { startSeconds, endSeconds };
}

function getImageUrl(item: ContentBlock, sources: SourceRecord[]) {
  const imageSource =
    sources.find((source) => source.type === "image" || source.type === "visual") ??
    sources.find((source) => source.url || source.localPath);
  return item.url ?? item.src ?? item.imageUrl ?? imageSource?.localPath ?? imageSource?.url;
}

function getImageAlt(item: ContentBlock, sources: SourceRecord[]) {
  const imageSource = sources.find((source) => source.type === "image" || source.type === "visual") ?? sources[0];
  return item.alt ?? item.title ?? imageSource?.title ?? "Course image";
}

function imageCreditLine(item: ContentBlock) {
  return [item.credit, item.license, item.generatedBy ? `Generated by ${item.generatedBy}` : ""]
    .filter((value) => typeof value === "string" && value.trim())
    .join(" · ");
}

function stringItems(value: unknown): string[] {
  return Array.isArray(value)
    ? value.filter((item): item is string => typeof item === "string" && item.trim().length > 0).map((item) => item.trim())
    : [];
}

function workedExampleAnswer(block: ContentBlock): string {
  const rawAnswer = (block as Record<string, unknown>).workedAnswer ?? (block as Record<string, unknown>).answer;
  return typeof rawAnswer === "string" || typeof rawAnswer === "number" ? String(rawAnswer) : "";
}

function workedExampleCheckItems(block: ContentBlock): string[] {
  const checks = stringItems(block.checks);
  if (checks.length > 0) {
    return checks;
  }
  return typeof block.check === "string" && block.check.trim() ? [block.check.trim()] : [];
}

function workedExampleSteps(block: ContentBlock) {
  return Array.isArray(block.steps)
    ? block.steps.filter((step) => step && typeof step === "object")
    : [];
}

function equationBlockLines(block: ContentBlock): string[] {
  const lines = [
    ...(typeof block.equation === "string" && block.equation.trim() ? [block.equation.trim()] : []),
    ...stringItems(block.equations),
  ];
  if (lines.length > 0) {
    return lines;
  }
  const fallback = block.value ?? block.text ?? block.body;
  return typeof fallback === "string" && fallback.trim()
    ? fallback.split(/\r?\n/).map((line) => line.trim()).filter(Boolean)
    : [];
}

export default function EditableContentBlock({
  block,
  blockIndex,
  courseKey,
  sources,
  courseSourceIndex,
  sectionId,
  isEditMode,
  onBlockChange,
  onBlockDelete,
  onCitationClick,
  onMissingCitationClick,
  onQuizSubmissionChange,
  onQuizProgressChange,
  onProjectSubmissionChange,
}: EditableContentBlockProps) {
  const blockSources = getSourcesByIds(block.sourceIds, sources);
  const citationIndex = blockCitationIndex(block.sourceIds, courseSourceIndex);
  const updateBlock = (nextBlock: ContentBlock) => onBlockChange?.(sectionId, blockIndex, nextBlock);
  const deleteAction = (
    <DeleteBlockButton
      label="Delete block"
      onClick={() => promptForDeleteConfirmation(() => onBlockDelete?.(sectionId, blockIndex))}
    />
  );
  const blockCitation = (
    <BlockCitationBadge
      citationIndex={citationIndex}
      onCitationClick={onCitationClick}
      onMissingCitationClick={onMissingCitationClick}
    />
  );
  const editShell = (children: ReactNode, actions?: ReactNode, showTrailingCitation = true) => (
    <div className={`editable-block-shell ${isEditMode ? "editable-block-shell--active" : ""}`}>
      {isEditMode && <div className="content-block-delete-row">{deleteAction}</div>}
      {isEditMode && (
        <div className="content-block-edit-actions">
          {actions}
        </div>
      )}
      {children}
      {showTrailingCitation && blockCitation}
    </div>
  );

  switch (block.type) {
    case "text": {
      const bodyField = block.value !== undefined ? "value" : "text";
      const bodyValue = block.value ?? block.text;
      return editShell(
        <div className="text-block">
          {block.heading && (
            <h3 className="course-editable-line">
              <span className="course-editable-line-content">
                {renderCitationText(block.heading, onCitationClick)}
                {!bodyValue && blockCitation}
              </span>
              {isEditMode && (
                <EditPencilButton
                  label="Edit text heading"
                  onClick={() => promptForText("Edit text heading", block.heading, (heading) => updateBlock({ ...block, heading }))}
                />
              )}
            </h3>
          )}
          {bodyValue && (
            <p className="course-editable-line">
              <span className="course-editable-line-content">
                {renderCitationText(bodyValue, onCitationClick)}
                {blockCitation}
              </span>
              {isEditMode && (
                <EditPencilButton
                  label="Edit text block"
                  onClick={() => promptForText("Edit text block", bodyValue, (value) => updateBlock({ ...block, [bodyField]: value }))}
                />
              )}
            </p>
          )}
        </div>,
        undefined,
        false,
      );
    }

    case "conceptCards":
    case "concept_cards":
      return (
        <ConceptCardStack
          block={block}
          citation={blockCitation}
          isEditMode={isEditMode}
          onBlockChange={updateBlock}
          onBlockDelete={() => promptForDeleteConfirmation(() => onBlockDelete?.(sectionId, blockIndex))}
        />
      );

    case "conceptCard":
    case "concept_card": {
      const title = block.title ?? block.heading ?? block.name ?? "Concept title";
      const body = block.description ?? block.body ?? block.value ?? block.text;

      return editShell(
        <article className="concept-card concept-card--single">
          <div className="course-editable-line">
            <h4>
              {title}
              {!body && blockCitation}
            </h4>
            {isEditMode && (
              <EditPencilButton
                label="Edit concept title"
                onClick={() => promptForText("Edit concept title", title, (nextTitle) => updateBlock({ ...block, title: nextTitle }))}
              />
            )}
          </div>
          <div className="course-editable-line">
            {body && (
              <p>
                {body}
                {blockCitation}
              </p>
            )}
            {isEditMode && (
              <EditPencilButton
                label="Edit concept description"
                onClick={() => promptForText("Edit concept description", body, (description) => updateBlock({ ...block, description }))}
              />
            )}
          </div>
        </article>,
        undefined,
        false,
      );
    }

    case "heading": {
      const heading = block.title ?? block.heading ?? block.value ?? block.text ?? "Heading title";
      return editShell(
        <h3 className="course-editable-line content-heading-block">
          <span className="course-editable-line-content">
            {renderCitationText(heading, onCitationClick)}
            {blockCitation}
          </span>
          {isEditMode && (
            <EditPencilButton
              label="Edit heading"
              onClick={() => promptForText("Edit heading", heading, (title) => updateBlock({ ...block, title }))}
            />
          )}
        </h3>,
        undefined,
        false,
      );
    }

    case "equation":
    case "equationBlock":
    case "equation_block": {
      const title = block.title ?? block.heading ?? "";
      const lines = equationBlockLines(block);
      const caption = block.caption ?? block.description ?? "";

      return editShell(
        <figure className="equation-block">
          {title && (
            <figcaption className="equation-block-title course-editable-line">
              <span className="course-editable-line-content">{renderCitationText(title, onCitationClick)}</span>
              {isEditMode && (
                <EditPencilButton
                  label="Edit equation title"
                  onClick={() => promptForText("Edit equation title", title, (nextTitle) => updateBlock({ ...block, title: nextTitle }))}
                />
              )}
            </figcaption>
          )}
          <div className="equation-block-lines" aria-label={title || "Equation"}>
            {(lines.length > 0 ? lines : ["equation = value"]).map((equation, equationIndex) => (
              <code key={`${equationIndex}-${equation}`}>{equation}</code>
            ))}
          </div>
          {caption && (
            <figcaption className="equation-block-caption course-editable-line">
              <span className="course-editable-line-content">{renderCitationText(caption, onCitationClick)}</span>
              {isEditMode && (
                <EditPencilButton
                  label="Edit equation caption"
                  onClick={() => promptForText("Edit equation caption", caption, (nextCaption) => updateBlock({ ...block, caption: nextCaption }))}
                />
              )}
            </figcaption>
          )}
        </figure>,
        <EditPencilButton
          label="Edit equation lines"
          onClick={() => promptForText("Edit equation lines", lines.join("\n"), (value) => updateBlock({
            ...block,
            equations: value
              .split(/\r?\n/)
              .map((line) => line.trim())
              .filter(Boolean),
          }))}
        />,
      );
    }

    case "workedExample":
    case "worked_example": {
      const title = block.title ?? block.heading ?? "Worked example";
      const problem = block.problem ?? block.value ?? block.text ?? "";
      const given = stringItems(block.given);
      const find = stringItems(block.find);
      const steps = workedExampleSteps(block);
      const answer = workedExampleAnswer(block);
      const checks = workedExampleCheckItems(block);

      return editShell(
        <article className="worked-example-block">
          <div className="worked-example-header course-editable-line">
            <h3 className="course-editable-line-content">
              {renderCitationText(title, onCitationClick)}
              {!problem && blockCitation}
            </h3>
            {isEditMode && (
              <EditPencilButton
                label="Edit worked example title"
                onClick={() => promptForText("Edit worked example title", title, (nextTitle) => updateBlock({ ...block, title: nextTitle }))}
              />
            )}
          </div>

          {problem && (
            <div className="worked-example-section">
              <h4>Problem</h4>
              <p className="course-editable-line">
                <span className="course-editable-line-content">
                  {renderCitationText(problem, onCitationClick)}
                </span>
                {isEditMode && (
                  <EditPencilButton
                    label="Edit worked example problem"
                    onClick={() => promptForText("Edit worked example problem", problem, (nextProblem) => updateBlock({ ...block, problem: nextProblem }))}
                  />
                )}
              </p>
            </div>
          )}

          {(given.length > 0 || find.length > 0) && (
            <div className="worked-example-two-column">
              {given.length > 0 && <WorkedExampleList title="Given" items={given} onCitationClick={onCitationClick} />}
              {find.length > 0 && <WorkedExampleList title="Find" items={find} onCitationClick={onCitationClick} />}
            </div>
          )}

          {steps.length > 0 && (
            <div className="worked-example-section">
              <h4>Solution</h4>
              <ol className="worked-example-steps">
                {steps.map((step, stepIndex) => {
                  const equations = [
                    ...(typeof step.equation === "string" && step.equation.trim() ? [step.equation.trim()] : []),
                    ...stringItems(step.equations),
                  ];
                  return (
                    <li key={`${stepIndex}-${step.explanation ?? equations.join("|")}`}>
                      {step.explanation && <p>{renderCitationText(step.explanation, onCitationClick)}</p>}
                      {equations.length > 0 && (
                        <div className="worked-example-equations" aria-label={`Equation step ${stepIndex + 1}`}>
                          {equations.map((equation, equationIndex) => (
                            <code key={`${equationIndex}-${equation}`}>{equation}</code>
                          ))}
                        </div>
                      )}
                    </li>
                  );
                })}
              </ol>
            </div>
          )}

          {answer && (
            <div className="worked-example-answer">
              <h4>Answer</h4>
              <p>{renderCitationText(answer, onCitationClick)}</p>
            </div>
          )}

          {checks.length > 0 && <WorkedExampleList title="Check" items={checks} onCitationClick={onCitationClick} />}
        </article>,
        <>
          <EditPencilButton
            label="Edit worked example title"
            onClick={() => promptForText("Edit worked example title", title, (nextTitle) => updateBlock({ ...block, title: nextTitle }))}
          />
          <EditPencilButton
            label="Edit worked example answer"
            onClick={() => promptForText("Edit worked example answer", answer, (workedAnswer) => updateBlock({ ...block, workedAnswer }))}
          />
        </>,
      );
    }

    case "image":
    case "visual": {
      const imageUrl = getImageUrl(block, blockSources);
      const imageAlt = getImageAlt(block, blockSources);
      const imageCaption = block.caption ?? block.description ?? "";
      const creditLine = imageCreditLine(block);

      return editShell(
        <figure className="image-block">
          {imageUrl ? (
            <img src={imageUrl} alt={imageAlt} loading="lazy" />
          ) : (
            <div className="image-block-placeholder">Image source unavailable.</div>
          )}
          {imageCaption || creditLine ? (
            <figcaption>
              {imageCaption && <span>{imageCaption}</span>}
              {creditLine && <small>{creditLine}</small>}
              {blockCitation}
            </figcaption>
          ) : (
            <div className="image-block-citation-row">{blockCitation}</div>
          )}
        </figure>,
        <>
          <EditPencilButton
            label="Edit image URL"
            onClick={() => promptForText("Edit image URL", imageUrl, (url) => updateBlock({ ...block, url }))}
          />
          <EditPencilButton
            label="Edit image alt text"
            onClick={() => promptForText("Edit image alt text", imageAlt, (alt) => updateBlock({ ...block, alt }))}
          />
          <EditPencilButton
            label="Edit image caption"
            onClick={() => promptForText("Edit image caption", imageCaption, (caption) => updateBlock({ ...block, caption }))}
          />
        </>,
        false,
      );
    }

    case "video": {
      const videoSource = blockSources.find((source) => source.embedUrl) ?? blockSources[0];
      const videoUrl = block.url ?? videoSource?.embedUrl ?? videoSource?.url;
      const clip = getVideoClip(block);
      const video = videoUrl ? (
        <VideoBlock url={videoUrl} title={videoSource?.title ?? block.title ?? "Video content"} clip={clip} />
      ) : (
        <p className="source-missing">Video source unavailable.</p>
      );

      return editShell(
        video,
        <EditPencilButton
          label="Edit video URL"
          onClick={() => promptForText("Edit video URL", videoUrl, (url) => updateBlock({ ...block, url }))}
        />,
      );
    }

    case "iframe": {
      const frameSource = blockSources[0];
      const frameUrl = block.url ?? frameSource?.embedUrl ?? frameSource?.url;
      const frameTitle = block.title ?? frameSource?.title ?? "Embedded resource";

      return editShell(
        <div className="iframe-block">
          {frameUrl ? (
            <iframe title={frameTitle} src={frameUrl} loading="lazy" />
          ) : (
            <p className="source-missing">Iframe source unavailable.</p>
          )}
        </div>,
        <>
          <EditPencilButton
            label="Edit iframe title"
            onClick={() => promptForText("Edit iframe title", frameTitle, (title) => updateBlock({ ...block, title }))}
          />
          <EditPencilButton
            label="Edit iframe URL"
            onClick={() => promptForText("Edit iframe URL", frameUrl, (url) => updateBlock({ ...block, url }))}
          />
        </>,
      );
    }

    case "quiz": {
      const quizKey = `quiz-${sectionId}-${blockIndex}`;
      return editShell(
        <QuizBlock
          data={block}
          name={quizKey}
          isEditMode={isEditMode}
          onDataChange={(nextData) => updateBlock({ ...block, ...nextData } as ContentBlock)}
          onSubmissionChange={onQuizSubmissionChange}
          onProgressChange={onQuizProgressChange}
        />,
        <EditPencilButton
          label="Edit quiz title"
          onClick={() => promptForText("Edit quiz title", block.title, (title) => updateBlock({ ...block, title }))}
        />,
      );
    }

    case "project":
      return editShell(
        <ProjectBlock
          block={block}
          courseKey={courseKey}
          isEditMode={isEditMode}
          onChange={updateBlock}
          sectionId={sectionId}
          sourceRecords={blockSources}
          onSubmissionChange={onProjectSubmissionChange}
        />,
        undefined,
      );

    case "game":
      return editShell(
        <div className="game-block">
          <p><strong>Game:</strong> {block.name || "Unnamed game"}</p>
          {block.description && <p>{block.description}</p>}
        </div>,
        <>
          <EditPencilButton
            label="Edit activity name"
            onClick={() => promptForText("Edit activity name", block.name, (name) => updateBlock({ ...block, name }))}
          />
          <EditPencilButton
            label="Edit activity description"
            onClick={() => promptForText("Edit activity description", block.description, (description) => updateBlock({ ...block, description }))}
          />
        </>,
      );

    default:
      return <p>Unknown content type</p>;
  }
}

function blockCitationIndex(sourceIds: string[] | undefined, courseSourceIndex: CourseSourceIndex) {
  if (!Array.isArray(sourceIds) || sourceIds.length === 0) {
    return null;
  }

  for (const sourceId of sourceIds) {
    const citationIndex = sourceCitationNumber(sourceId, courseSourceIndex);
    if (citationIndex !== null) {
      return citationIndex;
    }
  }

  return null;
}

function BlockCitationBadge({
  citationIndex,
  onCitationClick,
  onMissingCitationClick,
}: {
  citationIndex: number | null;
  onCitationClick?: (citationIndex: number) => void;
  onMissingCitationClick?: () => void;
}) {
  if (citationIndex !== null) {
    return (
      <sup className="block-citation">
        <button type="button" onClick={() => onCitationClick?.(citationIndex)} aria-label={`Open source ${citationIndex}`}>
          [{citationIndex}]
        </button>
      </sup>
    );
  }

  return (
    <sup className="block-citation block-citation--missing">
      <button
        type="button"
        onClick={onMissingCitationClick}
        aria-label="Add a source for this block"
        disabled={!onMissingCitationClick}
      >
        [!]
      </button>
    </sup>
  );
}

function WorkedExampleList({
  title,
  items,
  onCitationClick,
}: {
  title: string;
  items: string[];
  onCitationClick?: (citationIndex: number) => void;
}) {
  return (
    <div className="worked-example-section">
      <h4>{title}</h4>
      <ul>
        {items.map((item, index) => (
          <li key={`${index}-${item}`}>{renderCitationText(item, onCitationClick)}</li>
        ))}
      </ul>
    </div>
  );
}

function renderCitationText(value: string | undefined, onCitationClick?: (citationIndex: number) => void): ReactNode {
  if (!value || !onCitationClick) {
    return value;
  }

  const parts: ReactNode[] = [];
  const citationPattern = /\[(\d+)\]/g;
  let lastIndex = 0;
  let match: RegExpExecArray | null;

  while ((match = citationPattern.exec(value)) !== null) {
    if (match.index > lastIndex) {
      parts.push(value.slice(lastIndex, match.index));
    }

    const citationIndex = Number(match[1]);
    parts.push(
      <sup className="inline-citation" key={`${match.index}-${match[0]}`}>
        <button
          type="button"
          aria-label={`Open source ${citationIndex}`}
          onClick={() => onCitationClick(citationIndex)}
        >
          [{citationIndex}]
        </button>
      </sup>,
    );
    lastIndex = match.index + match[0].length;
  }

  if (lastIndex < value.length) {
    parts.push(value.slice(lastIndex));
  }

  return parts.length > 0 ? parts : value;
}
