from __future__ import annotations


PROGRAM_GROUP_RULES: list[tuple[str, str, list[str]]] = [
    (
        "life_sciences",
        "Biological and Life Sciences",
        [
            "biology",
            "biological",
            "cell biology",
            "genetics",
            "molecular biology",
            "anatomy",
            "physiology",
            "microbiology",
            "biochemistry",
        ],
    ),
    (
        "chemistry_physics",
        "Chemical and Physical Sciences",
        [
            "chemistry",
            "chemical",
            "general chemistry",
            "organic chemistry",
            "physics",
            "physical",
            "thermodynamics",
            "equilibrium",
            "acid",
            "base",
            "laboratory",
        ],
    ),
    (
        "quantitative_behavioral",
        "Quantitative and Behavioral Sciences",
        [
            "calculus",
            "statistics",
            "psychology",
            "sociology",
            "behavior",
            "behavioral",
            "social",
            "reasoning",
        ],
    ),
    (
        "clinical_readiness",
        "Clinical, Service, and Application Readiness",
        [
            "clinical",
            "service",
            "shadowing",
            "patient",
            "ethics",
            "interview",
            "application",
            "portfolio",
            "mcat",
            "medical school",
        ],
    ),
    (
        "foundations",
        "Foundations",
        [
            "foundation",
            "foundations",
            "introduction",
            "overview",
            "basics",
            "orientation",
            "safety",
            "measurement",
            "matter",
            "computer",
            "command line",
            "git",
        ],
    ),
    (
        "programming",
        "Programming and Computational Practice",
        ["programming", "python", "javascript", "typescript", "algorithm", "data structure", "function", "variable", "object", "software"],
    ),
    (
        "frontend",
        "Frontend and User Experience",
        ["html", "css", "react", "browser", "frontend", "accessibility", "interface", "user experience"],
    ),
    (
        "backend_data",
        "Backend, Data, and Infrastructure",
        ["api", "http", "authentication", "authorization", "server", "backend", "security", "database", "sql", "postgresql", "data", "deployment", "docker", "cloud", "operations"],
    ),
    (
        "analysis_modeling",
        "Analysis, Modeling, and Systems",
        ["statistics", "model", "modeling", "machine learning", "architecture", "systems", "design", "visualization", "equilibrium", "thermochemistry", "bonding", "stoichiometry", "periodic", "atomic", "reaction"],
    ),
    (
        "public_health",
        "Population, Policy, and Public Systems",
        ["epidemiology", "biostatistics", "policy", "community", "environmental health", "health equity", "intervention", "population"],
    ),
    (
        "practice_lab",
        "Practice, Laboratory, and Quality",
        ["lab", "laboratory", "practice", "experiment", "simulation", "testing", "quality", "evaluation"],
    ),
    (
        "professional",
        "Professional Evidence and Communication",
        ["communication", "documentation", "code review", "presentation", "portfolio", "ethics", "professional", "maintenance"],
    ),
]
