import type { LyciumProgram, LyciumRequirementOrigin } from "@lycium/contracts";

const benchmarkId = "benchmark-full-stack-engineer-curriculum-core";
const coreEvidenceRefs = ["acm-computing-curricula-2020", "software-engineering-2014", "swebok-v4"];

function academicOrigin(notes: string, frequency = 0.78): LyciumRequirementOrigin {
  return {
    originType: "common_academic_requirement",
    benchmarkIds: [benchmarkId],
    evidenceRefs: coreEvidenceRefs,
    frequency,
    notes,
  };
}

export const fullStackEngineerProgram: LyciumProgram = {
  id: "program-full-stack-engineer",
  title: "Full-Stack Engineer",
  description:
    "A source-backed professional pathway that turns programming, web systems, backend services, operations, and capstone work into a coherent full-stack engineering path.",
  programType: "career_path",
  field: "Software Engineering",
  level: "professional",
  targetOutcome:
    "Prepare learners to design, build, test, deploy, document, and explain a production-style full-stack web application with reviewable portfolio evidence.",
  learningOutcomes: [
    {
      id: "outcome-foundations",
      statement: "Use developer tools, version control, programming fundamentals, and web platform concepts inside a modern software project.",
    },
    {
      id: "outcome-frontend",
      statement: "Build accessible, testable, component-based browser interfaces with clear state and routing decisions.",
    },
    {
      id: "outcome-backend-data",
      statement: "Design backend APIs, persistence, authentication boundaries, and data-layer choices that are reliable and explainable.",
    },
    {
      id: "outcome-delivery-operations",
      statement: "Ship software through tests, CI/CD, deployment, observability, and operational feedback loops.",
    },
    {
      id: "outcome-portfolio-evidence",
      statement: "Produce portfolio artifacts that demonstrate implementation, testing, documentation, deployment, and architecture judgment.",
    },
  ],
  entryRequirements: [
    {
      id: "entry-basic-computer-literacy",
      type: "demonstrate_competency",
      competencyId: "basic-computer-literacy",
      title: "Basic computer literacy",
      required: true,
      importance: "required",
      origin: academicOrigin("Most professional software paths assume baseline computer, file-system, browser, and productivity-tool fluency.", 0.86),
    },
  ],
  requirementGroups: [
    {
      id: "cluster-programming-and-web-foundations",
      displayName: "Programming and Web Foundations",
      groupKind: "foundation",
      purpose:
        "Give learners the developer-tooling, programming, web-platform, and collaboration baseline needed before specialized frontend or backend work.",
      learningOutcomes: [
        {
          id: "cluster-outcome-use-foundations",
          statement: "Use programming fundamentals, source control, and web platform basics to implement small interactive features.",
        },
      ],
      requirements: [
        {
          id: "req-computing-systems-tools",
          type: "complete_course",
          courseId: "local-se-computing-systems",
          title: "Computing systems and developer tools",
          required: true,
          importance: "required",
          estimatedHours: 35,
          learningOutcomeIds: ["outcome-foundations"],
          origin: academicOrigin("Computing curricula commonly begin with systems, tooling, and computational foundations."),
        },
        {
          id: "req-git-collaboration",
          type: "complete_course",
          courseId: "local-se-git-collaboration",
          title: "Git, GitHub, and collaborative workflow",
          required: true,
          importance: "required",
          estimatedHours: 25,
          learningOutcomeIds: ["outcome-foundations"],
          origin: academicOrigin("Software engineering practice requires version-control and collaboration fluency."),
        },
        {
          id: "req-programming-language-foundation",
          type: "complete_n_of_courses",
          count: 1,
          courseIds: ["local-se-python-programming-i", "local-se-typescript-programming-i", "local-se-java-programming-i"],
          title: "Complete one programming language foundation",
          required: true,
          importance: "required",
          estimatedHours: 45,
          learningOutcomeIds: ["outcome-foundations"],
          origin: academicOrigin("Introductory programming is a common mandatory prerequisite for later software construction."),
        },
        {
          id: "req-web-platform-foundation",
          type: "complete_course",
          courseId: "local-se-web-platform",
          title: "Web platform foundations",
          required: true,
          importance: "required",
          estimatedHours: 45,
          learningOutcomeIds: ["outcome-foundations", "outcome-frontend"],
          origin: academicOrigin("Full-stack paths require browser, HTTP, HTML, CSS, accessibility, and DOM foundations."),
        },
      ],
      completionRule: { type: "complete_all" },
      estimatedHours: 150,
      masteryPolicy: {
        minimumMasteryPercent: 80,
        minimumAssessmentPercent: 70,
        remediationPolicy: "recommended",
      },
    },
    {
      id: "cluster-programming-core",
      displayName: "Programming Core",
      groupKind: "cluster",
      purpose:
        "Build durable programming fluency through data structures, software design, algorithmic thinking, and testable construction.",
      learningOutcomes: [
        {
          id: "cluster-outcome-programming-core",
          statement: "Write, organize, test, and reason about programs using reusable abstractions and data structures.",
        },
      ],
      requirements: [
        {
          id: "req-programming-depth",
          type: "complete_n_of_courses",
          count: 1,
          courseIds: ["local-se-python-programming-ii", "local-se-typescript-programming-ii", "local-se-java-programming-ii"],
          title: "Complete one second programming course",
          required: true,
          importance: "required",
          estimatedHours: 45,
          learningOutcomeIds: ["outcome-foundations"],
          origin: academicOrigin("A second programming course is a common bridge into data structures, design, and larger software projects."),
        },
        {
          id: "req-data-structures",
          type: "complete_course",
          courseId: "local-se-data-structures",
          title: "Data structures",
          required: true,
          importance: "required",
          estimatedHours: 50,
          learningOutcomeIds: ["outcome-foundations"],
          origin: academicOrigin("Data structures are a standard core requirement in computing and software engineering curricula."),
        },
        {
          id: "req-testing-quality-core",
          type: "complete_course",
          courseId: "local-se-testing-quality",
          title: "Testing, verification, and quality",
          required: true,
          importance: "required",
          estimatedHours: 45,
          learningOutcomeIds: ["outcome-delivery-operations"],
          origin: academicOrigin("Software engineering curricula emphasize verification, validation, and quality practices."),
        },
      ],
      completionRule: { type: "complete_all" },
      estimatedHours: 140,
      masteryPolicy: {
        minimumMasteryPercent: 80,
        minimumAssessmentPercent: 75,
        remediationPolicy: "recommended",
      },
      prerequisites: ["cluster-programming-and-web-foundations"],
    },
    {
      id: "cluster-frontend-engineering",
      displayName: "Frontend Engineering",
      groupKind: "cluster",
      purpose:
        "Move from browser fundamentals into accessible, stateful, tested frontend application engineering.",
      learningOutcomes: [
        {
          id: "cluster-outcome-frontend",
          statement: "Design and implement accessible, stateful, testable frontend experiences.",
        },
      ],
      requirements: [
        {
          id: "req-frontend-framework-choice",
          type: "complete_n_of_courses",
          count: 1,
          courseIds: ["local-se-frontend-react", "local-se-frontend-angular", "local-se-frontend-vue"],
          title: "Complete one frontend framework course",
          required: true,
          importance: "required",
          estimatedHours: 45,
          learningOutcomeIds: ["outcome-frontend"],
          origin: academicOrigin("Modern full-stack roles usually require a component-based frontend framework or equivalent UI architecture skill."),
        },
        {
          id: "req-frontend-testing",
          type: "complete_course",
          courseId: "local-se-frontend-testing",
          title: "Frontend testing",
          required: true,
          importance: "required",
          estimatedHours: 30,
          learningOutcomeIds: ["outcome-frontend", "outcome-delivery-operations"],
          origin: academicOrigin("Quality and accessibility checks are part of professional frontend engineering practice."),
        },
        {
          id: "req-product-ux-collaboration",
          type: "complete_course",
          courseId: "local-se-product-ux",
          title: "Product engineering and UX collaboration",
          required: true,
          importance: "recommended",
          estimatedHours: 35,
          learningOutcomeIds: ["outcome-frontend"],
          origin: academicOrigin("Frontend engineers frequently translate product, usability, and stakeholder constraints into interface decisions.", 0.64),
        },
      ],
      completionRule: { type: "complete_all" },
      estimatedHours: 110,
      masteryPolicy: {
        minimumMasteryPercent: 80,
        minimumAssessmentPercent: 75,
        remediationPolicy: "recommended",
      },
      prerequisites: ["cluster-programming-core"],
    },
    {
      id: "cluster-backend-and-data",
      displayName: "Backend and Data Layer",
      groupKind: "cluster",
      purpose:
        "Teach server-side application design, API contracts, persistence, authorization boundaries, and data reliability.",
      learningOutcomes: [
        {
          id: "cluster-outcome-backend-data",
          statement: "Design backend and data-layer choices that are reliable, secure, testable, and explainable.",
        },
      ],
      requirements: [
        {
          id: "req-api-design",
          type: "complete_course",
          courseId: "local-se-api-design",
          title: "HTTP APIs and service integration",
          required: true,
          importance: "required",
          estimatedHours: 40,
          learningOutcomeIds: ["outcome-backend-data"],
          origin: academicOrigin("Networked applications require API modeling, service boundaries, validation, and integration contracts."),
        },
        {
          id: "req-database-systems",
          type: "complete_course",
          courseId: "local-se-database-systems",
          title: "Database systems",
          required: true,
          importance: "required",
          estimatedHours: 45,
          learningOutcomeIds: ["outcome-backend-data"],
          origin: academicOrigin("Data management and persistence are standard computing and software engineering requirements."),
        },
        {
          id: "req-sql-data-modeling",
          type: "complete_course",
          courseId: "local-se-sql-data-modeling",
          title: "SQL and relational data modeling",
          required: true,
          importance: "required",
          estimatedHours: 35,
          learningOutcomeIds: ["outcome-backend-data"],
          origin: academicOrigin("Relational modeling and SQL remain common foundations for application data layers."),
        },
        {
          id: "req-backend-runtime-choice",
          type: "complete_n_of_courses",
          count: 1,
          courseIds: ["local-se-backend-node", "local-se-backend-python", "local-se-backend-java"],
          title: "Complete one backend runtime course",
          required: true,
          importance: "required",
          estimatedHours: 45,
          learningOutcomeIds: ["outcome-backend-data"],
          origin: academicOrigin("A full-stack pathway should include at least one server-side implementation stack."),
        },
        {
          id: "req-secure-software",
          type: "complete_course",
          courseId: "local-se-secure-software",
          title: "Secure software engineering",
          required: true,
          importance: "required",
          estimatedHours: 45,
          learningOutcomeIds: ["outcome-backend-data", "outcome-delivery-operations"],
          origin: academicOrigin("Security is a standard professional responsibility for networked software systems."),
        },
      ],
      completionRule: { type: "complete_all" },
      estimatedHours: 210,
      masteryPolicy: {
        minimumMasteryPercent: 80,
        minimumAssessmentPercent: 75,
        remediationPolicy: "recommended",
      },
      prerequisites: ["cluster-programming-core"],
    },
    {
      id: "cluster-delivery-and-operations",
      displayName: "Delivery and Operations",
      groupKind: "cluster",
      purpose:
        "Move applications from local implementation into tested, deployed, observable, maintainable systems.",
      learningOutcomes: [
        {
          id: "cluster-outcome-delivery",
          statement: "Use deployment, CI/CD, reliability, and operational practices to ship with confidence.",
        },
      ],
      requirements: [
        {
          id: "req-linux-networking",
          type: "complete_course",
          courseId: "local-se-linux-networking",
          title: "Linux and networking for developers",
          required: true,
          importance: "required",
          estimatedHours: 35,
          learningOutcomeIds: ["outcome-delivery-operations"],
          origin: academicOrigin("Deployment and operations require operating-system and networking fluency."),
        },
        {
          id: "req-containers-orchestration",
          type: "complete_course",
          courseId: "local-se-containers-orchestration",
          title: "Containers and orchestration",
          required: true,
          importance: "required",
          estimatedHours: 35,
          learningOutcomeIds: ["outcome-delivery-operations"],
          origin: academicOrigin("Containerization is a common modern deployment and environment-management primitive.", 0.66),
        },
        {
          id: "req-ci-cd-release",
          type: "complete_course",
          courseId: "local-se-ci-cd-release",
          title: "CI/CD and release engineering",
          required: true,
          importance: "required",
          estimatedHours: 35,
          learningOutcomeIds: ["outcome-delivery-operations"],
          origin: academicOrigin("Professional software programs emphasize repeatable testing, integration, and delivery workflows."),
        },
        {
          id: "req-cloud-platform-choice",
          type: "complete_n_of_courses",
          count: 1,
          courseIds: ["local-se-cloud-aws", "local-se-cloud-azure", "local-se-cloud-gcp"],
          title: "Complete one cloud foundations course",
          required: true,
          importance: "recommended",
          estimatedHours: 35,
          learningOutcomeIds: ["outcome-delivery-operations"],
          origin: academicOrigin("Cloud deployment is a common professional full-stack expectation, though specific providers vary.", 0.58),
        },
        {
          id: "req-observability-reliability",
          type: "complete_course",
          courseId: "local-se-observability-reliability",
          title: "Observability and reliability engineering",
          required: true,
          importance: "required",
          estimatedHours: 40,
          learningOutcomeIds: ["outcome-delivery-operations"],
          origin: academicOrigin("Operational feedback, reliability, and monitoring practices connect shipped software to user value."),
        },
      ],
      completionRule: { type: "complete_all" },
      estimatedHours: 180,
      masteryPolicy: {
        minimumMasteryPercent: 80,
        minimumAssessmentPercent: 75,
        remediationPolicy: "recommended",
      },
      prerequisites: ["cluster-frontend-engineering", "cluster-backend-and-data"],
    },
    {
      id: "cluster-specialization-electives",
      displayName: "Specialization Electives",
      groupKind: "elective_pool",
      purpose:
        "Let learners add depth in AI applications, security, distributed systems, mobile, or data engineering while preserving the full-stack core.",
      learningOutcomes: [
        {
          id: "cluster-outcome-specialization",
          statement: "Deepen one professional specialty without breaking the core full-stack pathway.",
        },
      ],
      requirements: [
        {
          id: "req-specialization-electives",
          type: "complete_n_of_courses",
          count: 2,
          courseIds: [
            "local-se-ai-app-engineering",
            "local-se-llm-product-patterns",
            "local-se-application-security",
            "local-se-distributed-systems",
            "local-se-mobile-app-engineering",
            "local-se-data-engineering",
          ],
          title: "Choose two specialization courses",
          required: true,
          importance: "alternate",
          estimatedHours: 90,
          learningOutcomeIds: ["outcome-portfolio-evidence"],
          origin: academicOrigin("Professional pathways commonly allow electives or concentrations after core requirements are satisfied.", 0.72),
        },
      ],
      completionRule: { type: "complete_n_of", count: 1 },
      estimatedHours: 90,
      masteryPolicy: {
        minimumMasteryPercent: 75,
        remediationPolicy: "optional",
      },
      prerequisites: ["cluster-frontend-engineering", "cluster-backend-and-data"],
    },
    {
      id: "cluster-capstone-and-readiness",
      displayName: "Capstone and Professional Evidence",
      groupKind: "capstone",
      purpose:
        "Convert completed learning into a shipped artifact, architecture narrative, documentation, and readiness evidence.",
      learningOutcomes: [
        {
          id: "cluster-outcome-capstone",
          statement: "Build, document, deploy, and present a production-style full-stack portfolio project.",
        },
      ],
      requirements: [
        {
          id: "req-capstone-studio-i",
          type: "complete_course",
          courseId: "local-se-capstone-i",
          title: "Software engineering capstone studio I",
          required: true,
          importance: "required",
          estimatedHours: 60,
          learningOutcomeIds: ["outcome-portfolio-evidence"],
          origin: academicOrigin("Substantial software engineering programs typically culminate in integrative project work."),
        },
        {
          id: "req-capstone-studio-ii",
          type: "complete_course",
          courseId: "local-se-capstone-ii",
          title: "Software engineering capstone studio II",
          required: true,
          importance: "required",
          estimatedHours: 60,
          learningOutcomeIds: ["outcome-portfolio-evidence"],
          origin: academicOrigin("A second capstone phase gives room for hardening, documentation, deployment, and review."),
        },
        {
          id: "req-portfolio-career-readiness",
          type: "complete_course",
          courseId: "local-se-portfolio-career",
          title: "Portfolio and career readiness",
          required: true,
          importance: "recommended",
          estimatedHours: 30,
          learningOutcomeIds: ["outcome-portfolio-evidence"],
          origin: academicOrigin("Professional readiness work turns technical output into reviewable evidence and career narrative.", 0.62),
        },
        {
          id: "req-submit-full-stack-capstone",
          type: "submit_project",
          projectId: "full-stack-portfolio-capstone",
          title: "Submit full-stack portfolio capstone",
          required: true,
          importance: "required",
          estimatedHours: 20,
          learningOutcomeIds: ["outcome-portfolio-evidence"],
          origin: academicOrigin("Portfolio artifacts provide evidence that completion means demonstrated capability, not only seat time."),
        },
        {
          id: "req-pass-readiness-review",
          type: "pass_assessment",
          assessmentId: "full-stack-readiness-review",
          title: "Pass full-stack readiness review",
          minScore: 80,
          required: true,
          importance: "required",
          estimatedHours: 5,
          learningOutcomeIds: ["outcome-portfolio-evidence"],
          origin: academicOrigin("Human or rubric-based review is important for career-path credential confidence.", 0.7),
        },
      ],
      completionRule: { type: "complete_all" },
      estimatedHours: 175,
      masteryPolicy: {
        minimumMasteryPercent: 85,
        minimumAssessmentPercent: 80,
        requiresCapstone: true,
        remediationPolicy: "required",
      },
      prerequisites: ["cluster-delivery-and-operations", "cluster-specialization-electives"],
    },
  ],
  estimatedHours: 1055,
  masteryPolicy: {
    minimumMasteryPercent: 85,
    minimumAssessmentPercent: 80,
    requiresCapstone: true,
    remediationPolicy: "required",
  },
  credentialPolicy: {
    credentialType: "portfolio_record",
    title: "Full-Stack Engineer Pathway Record",
    issuer: "Lycium",
    requiresHumanReview: true,
  },
  dependencyGraph: {
    edges: [
      {
        fromNodeId: "cluster-programming-and-web-foundations",
        toNodeId: "cluster-programming-core",
        type: "required",
        rationale: "Programming depth assumes developer tools, version control, and web basics.",
      },
      {
        fromNodeId: "cluster-programming-core",
        toNodeId: "cluster-frontend-engineering",
        type: "required",
        rationale: "Frontend engineering depends on programming fluency and testable software construction.",
      },
      {
        fromNodeId: "cluster-programming-core",
        toNodeId: "cluster-backend-and-data",
        type: "required",
        rationale: "Backend and data work require core programming fluency.",
      },
      {
        fromNodeId: "cluster-frontend-engineering",
        toNodeId: "cluster-delivery-and-operations",
        type: "required",
        rationale: "Delivery work should include at least one complete client application path.",
      },
      {
        fromNodeId: "cluster-backend-and-data",
        toNodeId: "cluster-delivery-and-operations",
        type: "required",
        rationale: "Operations work should include API, data, and security context.",
      },
      {
        fromNodeId: "cluster-delivery-and-operations",
        toNodeId: "cluster-capstone-and-readiness",
        type: "required",
        rationale: "The capstone should demonstrate deployed, observable, and supportable software.",
      },
      {
        fromNodeId: "cluster-specialization-electives",
        toNodeId: "cluster-capstone-and-readiness",
        type: "recommended",
        rationale: "Elective depth can make the capstone more distinctive and job-relevant.",
      },
    ],
  },
  version: "0.2.0",
  reviewStatus: "reviewed",
};

export default fullStackEngineerProgram;
