import type { CourseData, CourseEntry } from "../../courseTypes";
import { buildSoftwareEngineeringCourseModules, selectSoftwareEngineeringSourceIds } from "./softwareEngineeringCourseBuilder";

type WrapperInput = {
  key: string;
  title: string;
  shortDescription: string;
  tags: string[];
  difficultyLevel: string;
  estimatedHours: number;
  prerequisites?: string[];
};

const COURSE_TITLES: Record<string, string> = {
  "local-se-computing-systems": "Computing Systems and Developer Tools",
  "local-se-git-collaboration": "Git, GitHub, and Collaborative Workflow",
  "local-se-python-programming-i": "Programming I: Python",
  "local-se-python-programming-ii": "Programming II: Python Software Design",
  "local-se-typescript-programming-i": "Programming I: TypeScript",
  "local-se-typescript-programming-ii": "Programming II: TypeScript Software Design",
  "local-se-java-programming-i": "Programming I: Java",
  "local-se-java-programming-ii": "Programming II: Java Software Design",
  "local-se-discrete-math": "Discrete Mathematics for Computing",
  "local-se-calculus-computing": "Calculus for Computing",
  "local-se-linear-algebra": "Linear Algebra for Software Systems",
  "local-se-probability-statistics": "Probability and Statistics for Software Engineering",
  "local-se-data-structures": "Data Structures",
  "local-se-algorithms": "Algorithm Design and Analysis",
  "local-se-computer-organization": "Computer Organization",
  "local-se-operating-systems": "Operating Systems",
  "local-se-computer-networks": "Computer Networks",
  "local-se-database-systems": "Database Systems",
  "local-se-sql-data-modeling": "SQL and Relational Data Modeling",
  "local-se-data-privacy-governance": "Data Privacy and Governance",
  "local-se-requirements-engineering": "Requirements Engineering",
  "local-se-design-patterns": "Software Design Patterns",
  "local-se-software-architecture": "Software Architecture",
  "local-se-software-construction": "Software Construction",
  "local-se-testing-quality": "Testing, Verification, and Quality",
  "local-se-secure-software": "Secure Software Engineering",
  "local-se-web-platform": "Web Platform Foundations",
  "local-se-frontend-react": "Frontend Engineering with React",
  "local-se-frontend-angular": "Frontend Engineering with Angular",
  "local-se-frontend-vue": "Frontend Engineering with Vue",
  "local-se-frontend-testing": "Frontend Testing",
  "local-se-api-design": "HTTP APIs and Service Integration",
  "local-se-backend-node": "Backend Engineering with Node.js",
  "local-se-backend-python": "Backend Engineering with Python",
  "local-se-backend-java": "Backend Engineering with Java",
  "local-se-linux-networking": "Linux and Networking for Developers",
  "local-se-containers-orchestration": "Containers and Orchestration",
  "local-se-ci-cd-release": "CI/CD and Release Engineering",
  "local-se-cloud-aws": "Cloud Foundations: AWS",
  "local-se-cloud-azure": "Cloud Foundations: Azure",
  "local-se-cloud-gcp": "Cloud Foundations: Google Cloud",
  "local-se-observability-reliability": "Observability and Reliability Engineering",
  "local-se-technical-communication": "Technical Communication for Engineers",
  "local-se-product-ux": "Product Engineering and UX Collaboration",
  "local-se-agile-studio": "Agile Project Studio",
  "local-se-ethics-law-computing": "Ethics, Law, and Responsible Computing",
  "local-se-ai-app-engineering": "AI Application Engineering",
  "local-se-ml-systems": "Machine Learning Systems Engineering",
  "local-se-llm-product-patterns": "LLM Product Patterns",
  "local-se-application-security": "Application Security",
  "local-se-threat-modeling": "Threat Modeling and Secure Design",
  "local-se-security-operations": "Security Operations for Software Teams",
  "local-se-distributed-systems": "Distributed Systems",
  "local-se-event-driven-architecture": "Event-Driven Architecture",
  "local-se-scalable-data-systems": "Scalable Data Systems",
  "local-se-mobile-app-engineering": "Mobile App Engineering",
  "local-se-cross-platform-mobile": "Cross-Platform Mobile Development",
  "local-se-mobile-quality-release": "Mobile Quality and Release",
  "local-se-data-engineering": "Data Engineering Foundations",
  "local-se-analytics-engineering": "Analytics Engineering",
  "local-se-stream-processing": "Stream Processing Systems",
  "local-se-capstone-i": "Software Engineering Capstone Studio I",
  "local-se-capstone-ii": "Software Engineering Capstone Studio II",
  "local-se-portfolio-career": "Portfolio and Career Readiness",
};

const COURSE_EQUIVALENCIES: Record<string, NonNullable<CourseData["courseEquivalencies"]>[number]> = {
  "local-se-computing-systems": { department: "CS", courseCode: "CS 100", title: "Computing and Information Systems" },
  "local-se-git-collaboration": { department: "SE", courseCode: "SE 110", title: "Software Tools and Version Control" },
  "local-se-python-programming-i": { department: "CS", courseCode: "CS 101", title: "Introduction to Programming I" },
  "local-se-python-programming-ii": { department: "CS", courseCode: "CS 102", title: "Introduction to Programming II" },
  "local-se-typescript-programming-i": { department: "CS", courseCode: "CS 101", title: "Introduction to Programming I" },
  "local-se-typescript-programming-ii": { department: "CS", courseCode: "CS 102", title: "Introduction to Programming II" },
  "local-se-java-programming-i": { department: "CS", courseCode: "CS 101", title: "Introduction to Programming I" },
  "local-se-java-programming-ii": { department: "CS", courseCode: "CS 102", title: "Introduction to Programming II" },
  "local-se-discrete-math": { department: "MATH", courseCode: "MATH 230", title: "Discrete Mathematics" },
  "local-se-calculus-computing": { department: "MATH", courseCode: "MATH 151", title: "Calculus I" },
  "local-se-linear-algebra": { department: "MATH", courseCode: "MATH 240", title: "Linear Algebra" },
  "local-se-probability-statistics": { department: "STAT", courseCode: "STAT 250", title: "Probability and Statistics for Engineers" },
  "local-se-data-structures": { department: "CS", courseCode: "CS 201", title: "Data Structures" },
  "local-se-algorithms": { department: "CS", courseCode: "CS 301", title: "Design and Analysis of Algorithms" },
  "local-se-computer-organization": { department: "CS", courseCode: "CS 240", title: "Computer Organization" },
  "local-se-operating-systems": { department: "CS", courseCode: "CS 350", title: "Operating Systems" },
  "local-se-computer-networks": { department: "CS", courseCode: "CS 360", title: "Computer Networks" },
  "local-se-database-systems": { department: "CS", courseCode: "CS 340", title: "Database Systems" },
  "local-se-sql-data-modeling": { department: "CS", courseCode: "CS 341", title: "Database Design and SQL" },
  "local-se-data-privacy-governance": { department: "INFO", courseCode: "INFO 360", title: "Data Privacy and Governance" },
  "local-se-requirements-engineering": { department: "SE", courseCode: "SE 301", title: "Software Requirements Engineering" },
  "local-se-design-patterns": { department: "SE", courseCode: "SE 320", title: "Software Design" },
  "local-se-software-architecture": { department: "SE", courseCode: "SE 420", title: "Software Architecture" },
  "local-se-software-construction": { department: "SE", courseCode: "SE 310", title: "Software Construction" },
  "local-se-testing-quality": { department: "SE", courseCode: "SE 350", title: "Software Testing and Quality Assurance" },
  "local-se-secure-software": { department: "SE", courseCode: "SE 430", title: "Secure Software Engineering" },
  "local-se-web-platform": { department: "CS", courseCode: "CS 220", title: "Web Programming" },
  "local-se-frontend-react": { department: "CS", courseCode: "CS 322", title: "Frontend Web Development" },
  "local-se-frontend-angular": { department: "CS", courseCode: "CS 322", title: "Frontend Web Development" },
  "local-se-frontend-vue": { department: "CS", courseCode: "CS 322", title: "Frontend Web Development" },
  "local-se-frontend-testing": { department: "SE", courseCode: "SE 352", title: "Frontend Testing" },
  "local-se-api-design": { department: "CS", courseCode: "CS 324", title: "Web Services and APIs" },
  "local-se-backend-node": { department: "CS", courseCode: "CS 325", title: "Server-Side Web Development" },
  "local-se-backend-python": { department: "CS", courseCode: "CS 325", title: "Server-Side Web Development" },
  "local-se-backend-java": { department: "CS", courseCode: "CS 325", title: "Server-Side Web Development" },
  "local-se-linux-networking": { department: "IT", courseCode: "IT 260", title: "Linux and Network Administration" },
  "local-se-containers-orchestration": { department: "SE", courseCode: "SE 372", title: "Cloud-Native Application Deployment" },
  "local-se-ci-cd-release": { department: "SE", courseCode: "SE 370", title: "DevOps and Release Engineering" },
  "local-se-cloud-aws": { department: "IT", courseCode: "IT 375", title: "Cloud Computing" },
  "local-se-cloud-azure": { department: "IT", courseCode: "IT 375", title: "Cloud Computing" },
  "local-se-cloud-gcp": { department: "IT", courseCode: "IT 375", title: "Cloud Computing" },
  "local-se-observability-reliability": { department: "SE", courseCode: "SE 471", title: "Site Reliability Engineering" },
  "local-se-technical-communication": { department: "ENGL", courseCode: "ENGL 302", title: "Technical Writing" },
  "local-se-product-ux": { department: "HCI", courseCode: "HCI 300", title: "Human-Computer Interaction" },
  "local-se-agile-studio": { department: "SE", courseCode: "SE 300", title: "Software Engineering Process" },
  "local-se-ethics-law-computing": { department: "CS", courseCode: "CS 305", title: "Ethics and Professional Issues in Computing" },
  "local-se-ai-app-engineering": { department: "CS", courseCode: "CS 470", title: "Artificial Intelligence" },
  "local-se-ml-systems": { department: "CS", courseCode: "CS 478", title: "Machine Learning Systems" },
  "local-se-llm-product-patterns": { department: "CS", courseCode: "CS 479", title: "AI Application Development" },
  "local-se-application-security": { department: "CYSE", courseCode: "CYSE 401", title: "Application Security" },
  "local-se-threat-modeling": { department: "CYSE", courseCode: "CYSE 420", title: "Secure Systems Design" },
  "local-se-security-operations": { department: "CYSE", courseCode: "CYSE 430", title: "Security Operations" },
  "local-se-distributed-systems": { department: "CS", courseCode: "CS 450", title: "Distributed Systems" },
  "local-se-event-driven-architecture": { department: "SE", courseCode: "SE 455", title: "Enterprise Integration Patterns" },
  "local-se-scalable-data-systems": { department: "CS", courseCode: "CS 445", title: "Scalable Data Systems" },
  "local-se-mobile-app-engineering": { department: "CS", courseCode: "CS 426", title: "Mobile Application Development" },
  "local-se-cross-platform-mobile": { department: "CS", courseCode: "CS 427", title: "Cross-Platform Mobile Development" },
  "local-se-mobile-quality-release": { department: "SE", courseCode: "SE 428", title: "Mobile Software Quality" },
  "local-se-data-engineering": { department: "CS", courseCode: "CS 465", title: "Data Engineering" },
  "local-se-analytics-engineering": { department: "INFO", courseCode: "INFO 365", title: "Analytics Engineering" },
  "local-se-stream-processing": { department: "CS", courseCode: "CS 466", title: "Stream Processing" },
  "local-se-capstone-i": { department: "SE", courseCode: "SE 491", title: "Software Engineering Capstone I" },
  "local-se-capstone-ii": { department: "SE", courseCode: "SE 492", title: "Software Engineering Capstone II" },
  "local-se-portfolio-career": { department: "SE", courseCode: "SE 493", title: "Professional Practice and Portfolio" },
};

const COURSE_CLASSIFICATIONS: Record<string, { category: string; department: string }> = {
  "local-se-computing-systems": { category: "computing-information-sciences", department: "information-technology" },
  "local-se-git-collaboration": { category: "computing-information-sciences", department: "software-engineering" },
  "local-se-python-programming-i": { category: "computing-information-sciences", department: "computer-science" },
  "local-se-python-programming-ii": { category: "computing-information-sciences", department: "computer-science" },
  "local-se-typescript-programming-i": { category: "computing-information-sciences", department: "computer-science" },
  "local-se-typescript-programming-ii": { category: "computing-information-sciences", department: "computer-science" },
  "local-se-java-programming-i": { category: "computing-information-sciences", department: "computer-science" },
  "local-se-java-programming-ii": { category: "computing-information-sciences", department: "computer-science" },
  "local-se-discrete-math": { category: "natural-sciences-mathematics", department: "mathematics" },
  "local-se-calculus-computing": { category: "natural-sciences-mathematics", department: "mathematics" },
  "local-se-linear-algebra": { category: "natural-sciences-mathematics", department: "mathematics" },
  "local-se-probability-statistics": { category: "natural-sciences-mathematics", department: "statistics" },
  "local-se-data-structures": { category: "computing-information-sciences", department: "computer-science" },
  "local-se-algorithms": { category: "computing-information-sciences", department: "computer-science" },
  "local-se-computer-organization": { category: "computing-information-sciences", department: "computer-science" },
  "local-se-operating-systems": { category: "computing-information-sciences", department: "computer-science" },
  "local-se-computer-networks": { category: "computing-information-sciences", department: "computer-science" },
  "local-se-database-systems": { category: "computing-information-sciences", department: "computer-science" },
  "local-se-sql-data-modeling": { category: "computing-information-sciences", department: "computer-science" },
  "local-se-data-privacy-governance": { category: "computing-information-sciences", department: "information-science" },
  "local-se-requirements-engineering": { category: "computing-information-sciences", department: "software-engineering" },
  "local-se-design-patterns": { category: "computing-information-sciences", department: "software-engineering" },
  "local-se-software-architecture": { category: "computing-information-sciences", department: "software-engineering" },
  "local-se-software-construction": { category: "computing-information-sciences", department: "software-engineering" },
  "local-se-testing-quality": { category: "computing-information-sciences", department: "software-engineering" },
  "local-se-secure-software": { category: "computing-information-sciences", department: "software-engineering" },
  "local-se-web-platform": { category: "computing-information-sciences", department: "computer-science" },
  "local-se-frontend-react": { category: "computing-information-sciences", department: "computer-science" },
  "local-se-frontend-angular": { category: "computing-information-sciences", department: "computer-science" },
  "local-se-frontend-vue": { category: "computing-information-sciences", department: "computer-science" },
  "local-se-frontend-testing": { category: "computing-information-sciences", department: "software-engineering" },
  "local-se-api-design": { category: "computing-information-sciences", department: "computer-science" },
  "local-se-backend-node": { category: "computing-information-sciences", department: "computer-science" },
  "local-se-backend-python": { category: "computing-information-sciences", department: "computer-science" },
  "local-se-backend-java": { category: "computing-information-sciences", department: "computer-science" },
  "local-se-linux-networking": { category: "computing-information-sciences", department: "information-technology" },
  "local-se-containers-orchestration": { category: "computing-information-sciences", department: "software-engineering" },
  "local-se-ci-cd-release": { category: "computing-information-sciences", department: "software-engineering" },
  "local-se-cloud-aws": { category: "computing-information-sciences", department: "information-technology" },
  "local-se-cloud-azure": { category: "computing-information-sciences", department: "information-technology" },
  "local-se-cloud-gcp": { category: "computing-information-sciences", department: "information-technology" },
  "local-se-observability-reliability": { category: "computing-information-sciences", department: "software-engineering" },
  "local-se-technical-communication": { category: "communication-media", department: "communication-studies" },
  "local-se-product-ux": { category: "computing-information-sciences", department: "human-computer-interaction" },
  "local-se-agile-studio": { category: "computing-information-sciences", department: "software-engineering" },
  "local-se-ethics-law-computing": { category: "computing-information-sciences", department: "computer-science" },
  "local-se-ai-app-engineering": { category: "computing-information-sciences", department: "artificial-intelligence" },
  "local-se-ml-systems": { category: "computing-information-sciences", department: "artificial-intelligence" },
  "local-se-llm-product-patterns": { category: "computing-information-sciences", department: "artificial-intelligence" },
  "local-se-application-security": { category: "computing-information-sciences", department: "cybersecurity" },
  "local-se-threat-modeling": { category: "computing-information-sciences", department: "cybersecurity" },
  "local-se-security-operations": { category: "computing-information-sciences", department: "cybersecurity" },
  "local-se-distributed-systems": { category: "computing-information-sciences", department: "computer-science" },
  "local-se-event-driven-architecture": { category: "computing-information-sciences", department: "software-engineering" },
  "local-se-scalable-data-systems": { category: "computing-information-sciences", department: "computer-science" },
  "local-se-mobile-app-engineering": { category: "computing-information-sciences", department: "computer-science" },
  "local-se-cross-platform-mobile": { category: "computing-information-sciences", department: "computer-science" },
  "local-se-mobile-quality-release": { category: "computing-information-sciences", department: "software-engineering" },
  "local-se-data-engineering": { category: "computing-information-sciences", department: "data-science" },
  "local-se-analytics-engineering": { category: "computing-information-sciences", department: "data-science" },
  "local-se-stream-processing": { category: "computing-information-sciences", department: "data-science" },
  "local-se-capstone-i": { category: "computing-information-sciences", department: "software-engineering" },
  "local-se-capstone-ii": { category: "computing-information-sciences", department: "software-engineering" },
  "local-se-portfolio-career": { category: "computing-information-sciences", department: "software-engineering" },
};

function prereq(courseId: string) {
  return {
    type: "course" as const,
    courseId,
    title: COURSE_TITLES[courseId] ?? courseId,
    required: true,
  };
}

function course(input: WrapperInput): CourseEntry {
  const prerequisites = input.prerequisites?.map(prereq) ?? [];
  const courseEquivalency = COURSE_EQUIVALENCIES[input.key];
  const classification = COURSE_CLASSIFICATIONS[input.key] ?? {
    category: "computing-information-sciences",
    department: "software-engineering",
  };
  const sourceIds = selectSoftwareEngineeringSourceIds(input);
  const data: CourseData = {
    title: input.title,
    shortDescription: input.shortDescription,
    difficultyLevel: input.difficultyLevel,
    category: classification.category,
    department: classification.department,
    tags: ["software engineering", ...input.tags],
    learningTypes: [],
    orderMandatory: false,
    sourceIds,
    courseEquivalencies: courseEquivalency
      ? [
          {
            institution: "Common university catalog analogue",
            notes: "Representative parity reference, not an articulation agreement.",
            ...courseEquivalency,
          },
        ]
      : undefined,
    prerequisites,
    metadata: {
      wrapperStatus: "built_generated_course",
      pacingLabel: "Module",
      estimatedHours: input.estimatedHours,
      prerequisiteCourseIds: input.prerequisites ?? [],
      programIds: ["program-software-engineering"],
      scope: {
        audience: "software engineering program learners",
        level: input.difficultyLevel,
        duration: `${input.estimatedHours} learning hours`,
        outcome: input.shortDescription,
        prerequisites: input.prerequisites ?? [],
        exclusions: ["formal transfer-credit claims", "vendor certification guarantees"],
      },
      generationPlan: {
        status: ["scoped", "modules_planned", "content_drafted", "assessment_drafted", "summary_drafted"],
        moduleCount: 10,
        unitsPerModule: 4,
        quizQuestionsPerModule: 10,
        sourceMap: sourceIds,
      },
    },
    modules: buildSoftwareEngineeringCourseModules({
      courseKey: input.key,
      title: input.title,
      shortDescription: input.shortDescription,
      tags: input.tags,
      difficultyLevel: input.difficultyLevel,
      estimatedHours: input.estimatedHours,
      sourceIds,
    }),
  };

  return { key: input.key, title: input.title, data, source: "local" };
}

const corePrereq = ["local-se-git-collaboration"];
const programmingPrereq = ["local-se-python-programming-ii"];
const structuresPrereq = ["local-se-data-structures"];
const webPrereq = ["local-se-web-platform"];
const backendPrereq = ["local-se-api-design", "local-se-database-systems"];
const operationsPrereq = ["local-se-linux-networking"];

export const softwareEngineeringCourseWrappers: CourseEntry[] = [
  course({ key: "local-se-computing-systems", title: COURSE_TITLES["local-se-computing-systems"], shortDescription: "A practical introduction to computers, shells, editors, files, and developer environments.", tags: ["computing", "developer tools"], difficultyLevel: "Foundational", estimatedHours: 25 }),
  course({ key: "local-se-git-collaboration", title: COURSE_TITLES["local-se-git-collaboration"], shortDescription: "Version control, branching, pull requests, code review, and collaborative repository habits.", tags: ["git", "collaboration"], difficultyLevel: "Foundational", estimatedHours: 25, prerequisites: ["local-se-computing-systems"] }),
  course({ key: "local-se-python-programming-i", title: COURSE_TITLES["local-se-python-programming-i"], shortDescription: "Programming fundamentals through Python syntax, control flow, functions, and small programs.", tags: ["programming", "python"], difficultyLevel: "Foundational", estimatedHours: 45, prerequisites: corePrereq }),
  course({ key: "local-se-python-programming-ii", title: COURSE_TITLES["local-se-python-programming-ii"], shortDescription: "Intermediate Python with modules, testing, files, errors, object design, and maintainable programs.", tags: ["programming", "python"], difficultyLevel: "Foundational", estimatedHours: 45, prerequisites: ["local-se-python-programming-i"] }),
  course({ key: "local-se-typescript-programming-i", title: COURSE_TITLES["local-se-typescript-programming-i"], shortDescription: "Programming fundamentals using TypeScript, browser-adjacent tooling, and typed functions.", tags: ["programming", "typescript"], difficultyLevel: "Foundational", estimatedHours: 45, prerequisites: corePrereq }),
  course({ key: "local-se-typescript-programming-ii", title: COURSE_TITLES["local-se-typescript-programming-ii"], shortDescription: "Intermediate TypeScript with modules, async code, tests, typed data models, and maintainable design.", tags: ["programming", "typescript"], difficultyLevel: "Foundational", estimatedHours: 45, prerequisites: ["local-se-typescript-programming-i"] }),
  course({ key: "local-se-java-programming-i", title: COURSE_TITLES["local-se-java-programming-i"], shortDescription: "Programming fundamentals using Java syntax, objects, control flow, and command-line projects.", tags: ["programming", "java"], difficultyLevel: "Foundational", estimatedHours: 45, prerequisites: corePrereq }),
  course({ key: "local-se-java-programming-ii", title: COURSE_TITLES["local-se-java-programming-ii"], shortDescription: "Intermediate Java with object-oriented design, collections, testing, exceptions, and packages.", tags: ["programming", "java"], difficultyLevel: "Foundational", estimatedHours: 45, prerequisites: ["local-se-java-programming-i"] }),
  course({ key: "local-se-discrete-math", title: COURSE_TITLES["local-se-discrete-math"], shortDescription: "Logic, sets, functions, relations, graphs, induction, and proof habits for computing.", tags: ["math", "discrete mathematics"], difficultyLevel: "Foundational", estimatedHours: 45 }),
  course({ key: "local-se-calculus-computing", title: COURSE_TITLES["local-se-calculus-computing"], shortDescription: "Limits, derivatives, integrals, and modeling ideas used in computing and optimization contexts.", tags: ["math", "calculus"], difficultyLevel: "Foundational", estimatedHours: 45 }),
  course({ key: "local-se-linear-algebra", title: COURSE_TITLES["local-se-linear-algebra"], shortDescription: "Vectors, matrices, transformations, decompositions, and geometric reasoning for software systems.", tags: ["math", "linear algebra"], difficultyLevel: "Intermediate", estimatedHours: 45, prerequisites: ["local-se-calculus-computing"] }),
  course({ key: "local-se-probability-statistics", title: COURSE_TITLES["local-se-probability-statistics"], shortDescription: "Probability, distributions, inference, uncertainty, experiments, and data-informed engineering decisions.", tags: ["math", "statistics"], difficultyLevel: "Intermediate", estimatedHours: 45, prerequisites: ["local-se-calculus-computing"] }),
  course({ key: "local-se-data-structures", title: COURSE_TITLES["local-se-data-structures"], shortDescription: "Lists, stacks, queues, trees, maps, graphs, complexity, and implementation tradeoffs.", tags: ["computer science", "data structures"], difficultyLevel: "Intermediate", estimatedHours: 50, prerequisites: programmingPrereq }),
  course({ key: "local-se-algorithms", title: COURSE_TITLES["local-se-algorithms"], shortDescription: "Algorithmic strategies, complexity analysis, recursion, dynamic programming, graph algorithms, and tradeoffs.", tags: ["computer science", "algorithms"], difficultyLevel: "Intermediate", estimatedHours: 50, prerequisites: structuresPrereq }),
  course({ key: "local-se-computer-organization", title: COURSE_TITLES["local-se-computer-organization"], shortDescription: "Hardware/software boundaries, memory, processors, data representation, and low-level execution.", tags: ["systems", "computer organization"], difficultyLevel: "Intermediate", estimatedHours: 45, prerequisites: programmingPrereq }),
  course({ key: "local-se-operating-systems", title: COURSE_TITLES["local-se-operating-systems"], shortDescription: "Processes, threads, memory, filesystems, scheduling, concurrency, and operating-system abstractions.", tags: ["systems", "operating systems"], difficultyLevel: "Intermediate", estimatedHours: 50, prerequisites: ["local-se-computer-organization", "local-se-data-structures"] }),
  course({ key: "local-se-computer-networks", title: COURSE_TITLES["local-se-computer-networks"], shortDescription: "Network layers, TCP/IP, DNS, HTTP, routing, reliability, latency, and distributed communication basics.", tags: ["systems", "networking"], difficultyLevel: "Intermediate", estimatedHours: 45, prerequisites: ["local-se-operating-systems"] }),
  course({ key: "local-se-database-systems", title: COURSE_TITLES["local-se-database-systems"], shortDescription: "Database architecture, storage, indexing, transactions, query planning, and reliability properties.", tags: ["data", "databases"], difficultyLevel: "Intermediate", estimatedHours: 45, prerequisites: structuresPrereq }),
  course({ key: "local-se-sql-data-modeling", title: COURSE_TITLES["local-se-sql-data-modeling"], shortDescription: "Relational modeling, SQL queries, normalization, constraints, migrations, and application data access.", tags: ["data", "sql"], difficultyLevel: "Intermediate", estimatedHours: 35, prerequisites: ["local-se-database-systems"] }),
  course({ key: "local-se-data-privacy-governance", title: COURSE_TITLES["local-se-data-privacy-governance"], shortDescription: "Data classification, retention, privacy principles, compliance basics, and responsible data handling.", tags: ["data", "privacy"], difficultyLevel: "Intermediate", estimatedHours: 30, prerequisites: ["local-se-sql-data-modeling"] }),
  course({ key: "local-se-requirements-engineering", title: COURSE_TITLES["local-se-requirements-engineering"], shortDescription: "Stakeholder analysis, user stories, constraints, acceptance criteria, scope, and requirements validation.", tags: ["requirements", "product"], difficultyLevel: "Intermediate", estimatedHours: 35, prerequisites: programmingPrereq }),
  course({ key: "local-se-design-patterns", title: COURSE_TITLES["local-se-design-patterns"], shortDescription: "Reusable design patterns, refactoring, dependency management, abstraction boundaries, and maintainability.", tags: ["design", "patterns"], difficultyLevel: "Intermediate", estimatedHours: 40, prerequisites: structuresPrereq }),
  course({ key: "local-se-software-architecture", title: COURSE_TITLES["local-se-software-architecture"], shortDescription: "Architecture views, quality attributes, tradeoff analysis, documentation, and system design decisions.", tags: ["architecture", "design"], difficultyLevel: "Advanced", estimatedHours: 55, prerequisites: ["local-se-design-patterns", "local-se-computer-networks", "local-se-database-systems"] }),
  course({ key: "local-se-software-construction", title: COURSE_TITLES["local-se-software-construction"], shortDescription: "Code organization, reviewability, configuration, error handling, dependency hygiene, and implementation discipline.", tags: ["construction", "code quality"], difficultyLevel: "Intermediate", estimatedHours: 45, prerequisites: ["local-se-design-patterns"] }),
  course({ key: "local-se-testing-quality", title: COURSE_TITLES["local-se-testing-quality"], shortDescription: "Unit, integration, contract, property, and end-to-end testing with quality strategy and risk analysis.", tags: ["testing", "quality"], difficultyLevel: "Intermediate", estimatedHours: 45, prerequisites: ["local-se-software-construction"] }),
  course({ key: "local-se-secure-software", title: COURSE_TITLES["local-se-secure-software"], shortDescription: "Secure design, common vulnerabilities, authentication risks, input handling, secrets, and threat-informed coding.", tags: ["security", "secure coding"], difficultyLevel: "Advanced", estimatedHours: 45, prerequisites: ["local-se-api-design", "local-se-testing-quality"] }),
  course({ key: "local-se-web-platform", title: COURSE_TITLES["local-se-web-platform"], shortDescription: "HTML, CSS, browser runtime, DOM, accessibility, HTTP basics, and progressive web foundations.", tags: ["web", "frontend"], difficultyLevel: "Foundational", estimatedHours: 45, prerequisites: programmingPrereq }),
  course({ key: "local-se-frontend-react", title: COURSE_TITLES["local-se-frontend-react"], shortDescription: "Component architecture, state, routing, effects, forms, and frontend application design with React.", tags: ["frontend", "react"], difficultyLevel: "Intermediate", estimatedHours: 45, prerequisites: webPrereq }),
  course({ key: "local-se-frontend-angular", title: COURSE_TITLES["local-se-frontend-angular"], shortDescription: "Component architecture, services, routing, forms, state, and frontend application design with Angular.", tags: ["frontend", "angular"], difficultyLevel: "Intermediate", estimatedHours: 45, prerequisites: webPrereq }),
  course({ key: "local-se-frontend-vue", title: COURSE_TITLES["local-se-frontend-vue"], shortDescription: "Component architecture, reactivity, routing, forms, state, and frontend application design with Vue.", tags: ["frontend", "vue"], difficultyLevel: "Intermediate", estimatedHours: 45, prerequisites: webPrereq }),
  course({ key: "local-se-frontend-testing", title: COURSE_TITLES["local-se-frontend-testing"], shortDescription: "Frontend unit, component, integration, accessibility, and browser testing strategies.", tags: ["frontend", "testing"], difficultyLevel: "Intermediate", estimatedHours: 30, prerequisites: webPrereq }),
  course({ key: "local-se-api-design", title: COURSE_TITLES["local-se-api-design"], shortDescription: "HTTP APIs, resource modeling, service boundaries, validation, versioning, errors, and integration contracts.", tags: ["backend", "apis"], difficultyLevel: "Intermediate", estimatedHours: 40, prerequisites: ["local-se-computer-networks", "local-se-web-platform"] }),
  course({ key: "local-se-backend-node", title: COURSE_TITLES["local-se-backend-node"], shortDescription: "Server-side application design, routing, persistence, jobs, and API implementation with Node.js.", tags: ["backend", "node"], difficultyLevel: "Intermediate", estimatedHours: 45, prerequisites: backendPrereq }),
  course({ key: "local-se-backend-python", title: COURSE_TITLES["local-se-backend-python"], shortDescription: "Server-side application design, routing, persistence, jobs, and API implementation with Python.", tags: ["backend", "python"], difficultyLevel: "Intermediate", estimatedHours: 45, prerequisites: backendPrereq }),
  course({ key: "local-se-backend-java", title: COURSE_TITLES["local-se-backend-java"], shortDescription: "Server-side application design, routing, persistence, jobs, and API implementation with Java.", tags: ["backend", "java"], difficultyLevel: "Intermediate", estimatedHours: 45, prerequisites: backendPrereq }),
  course({ key: "local-se-linux-networking", title: COURSE_TITLES["local-se-linux-networking"], shortDescription: "Linux command line, processes, permissions, networking tools, services, and operational debugging.", tags: ["operations", "linux"], difficultyLevel: "Intermediate", estimatedHours: 35, prerequisites: ["local-se-operating-systems", "local-se-computer-networks"] }),
  course({ key: "local-se-containers-orchestration", title: COURSE_TITLES["local-se-containers-orchestration"], shortDescription: "Images, containers, registries, orchestration concepts, local environments, and deployment packaging.", tags: ["operations", "containers"], difficultyLevel: "Intermediate", estimatedHours: 35, prerequisites: operationsPrereq }),
  course({ key: "local-se-ci-cd-release", title: COURSE_TITLES["local-se-ci-cd-release"], shortDescription: "Automated builds, test gates, release workflows, environments, rollback, and deployment safety.", tags: ["devops", "ci/cd"], difficultyLevel: "Intermediate", estimatedHours: 35, prerequisites: ["local-se-testing-quality", "local-se-containers-orchestration"] }),
  course({ key: "local-se-cloud-aws", title: COURSE_TITLES["local-se-cloud-aws"], shortDescription: "Core AWS compute, storage, networking, identity, deployment, and operational primitives.", tags: ["cloud", "aws"], difficultyLevel: "Intermediate", estimatedHours: 35, prerequisites: operationsPrereq }),
  course({ key: "local-se-cloud-azure", title: COURSE_TITLES["local-se-cloud-azure"], shortDescription: "Core Azure compute, storage, networking, identity, deployment, and operational primitives.", tags: ["cloud", "azure"], difficultyLevel: "Intermediate", estimatedHours: 35, prerequisites: operationsPrereq }),
  course({ key: "local-se-cloud-gcp", title: COURSE_TITLES["local-se-cloud-gcp"], shortDescription: "Core Google Cloud compute, storage, networking, identity, deployment, and operational primitives.", tags: ["cloud", "gcp"], difficultyLevel: "Intermediate", estimatedHours: 35, prerequisites: operationsPrereq }),
  course({ key: "local-se-observability-reliability", title: COURSE_TITLES["local-se-observability-reliability"], shortDescription: "Logs, metrics, traces, SLOs, incident response, reliability practices, and production feedback loops.", tags: ["operations", "reliability"], difficultyLevel: "Advanced", estimatedHours: 40, prerequisites: ["local-se-ci-cd-release"] }),
  course({ key: "local-se-technical-communication", title: COURSE_TITLES["local-se-technical-communication"], shortDescription: "Technical writing, architecture notes, decision records, diagrams, documentation, and engineering communication.", tags: ["communication", "documentation"], difficultyLevel: "Foundational", estimatedHours: 30 }),
  course({ key: "local-se-product-ux", title: COURSE_TITLES["local-se-product-ux"], shortDescription: "Product thinking, user research basics, UX collaboration, tradeoff framing, and outcome-oriented delivery.", tags: ["product", "ux"], difficultyLevel: "Intermediate", estimatedHours: 35, prerequisites: ["local-se-requirements-engineering"] }),
  course({ key: "local-se-agile-studio", title: COURSE_TITLES["local-se-agile-studio"], shortDescription: "Team planning, iteration, estimation, retrospectives, delivery rituals, and project coordination.", tags: ["teamwork", "agile"], difficultyLevel: "Intermediate", estimatedHours: 35, prerequisites: ["local-se-git-collaboration"] }),
  course({ key: "local-se-ethics-law-computing", title: COURSE_TITLES["local-se-ethics-law-computing"], shortDescription: "Professional ethics, legal basics, accessibility, privacy, fairness, safety, and social responsibility.", tags: ["ethics", "law"], difficultyLevel: "Intermediate", estimatedHours: 35 }),
  course({ key: "local-se-ai-app-engineering", title: COURSE_TITLES["local-se-ai-app-engineering"], shortDescription: "Designing AI-backed application features, workflows, evaluation loops, and user-facing reliability controls.", tags: ["ai", "application engineering"], difficultyLevel: "Advanced", estimatedHours: 45, prerequisites: ["local-se-api-design", "local-se-probability-statistics"] }),
  course({ key: "local-se-ml-systems", title: COURSE_TITLES["local-se-ml-systems"], shortDescription: "Production ML system architecture, data pipelines, model serving, monitoring, and lifecycle tradeoffs.", tags: ["machine learning", "systems"], difficultyLevel: "Advanced", estimatedHours: 50, prerequisites: ["local-se-ai-app-engineering"] }),
  course({ key: "local-se-llm-product-patterns", title: COURSE_TITLES["local-se-llm-product-patterns"], shortDescription: "LLM product architecture, retrieval patterns, prompt contracts, evaluations, safety, and UX constraints.", tags: ["llm", "ai product"], difficultyLevel: "Advanced", estimatedHours: 40, prerequisites: ["local-se-ai-app-engineering"] }),
  course({ key: "local-se-application-security", title: COURSE_TITLES["local-se-application-security"], shortDescription: "Application threat surfaces, secure implementation, auth risks, dependency risk, and vulnerability handling.", tags: ["security", "application security"], difficultyLevel: "Advanced", estimatedHours: 45, prerequisites: ["local-se-secure-software"] }),
  course({ key: "local-se-threat-modeling", title: COURSE_TITLES["local-se-threat-modeling"], shortDescription: "Threat modeling methods, abuse cases, trust boundaries, mitigations, and secure architecture review.", tags: ["security", "threat modeling"], difficultyLevel: "Advanced", estimatedHours: 35, prerequisites: ["local-se-application-security"] }),
  course({ key: "local-se-security-operations", title: COURSE_TITLES["local-se-security-operations"], shortDescription: "Security monitoring, incident coordination, vulnerability response, logging, and operational controls.", tags: ["security", "operations"], difficultyLevel: "Advanced", estimatedHours: 35, prerequisites: ["local-se-application-security", "local-se-observability-reliability"] }),
  course({ key: "local-se-distributed-systems", title: COURSE_TITLES["local-se-distributed-systems"], shortDescription: "Distributed communication, consistency, replication, consensus, failure modes, and system tradeoffs.", tags: ["distributed systems", "systems"], difficultyLevel: "Advanced", estimatedHours: 50, prerequisites: ["local-se-computer-networks", "local-se-operating-systems"] }),
  course({ key: "local-se-event-driven-architecture", title: COURSE_TITLES["local-se-event-driven-architecture"], shortDescription: "Events, queues, streams, sagas, delivery guarantees, integration boundaries, and asynchronous workflows.", tags: ["architecture", "events"], difficultyLevel: "Advanced", estimatedHours: 40, prerequisites: ["local-se-distributed-systems"] }),
  course({ key: "local-se-scalable-data-systems", title: COURSE_TITLES["local-se-scalable-data-systems"], shortDescription: "Scaling persistence, caching, partitioning, replication, query workload design, and data reliability.", tags: ["data", "scalability"], difficultyLevel: "Advanced", estimatedHours: 40, prerequisites: ["local-se-distributed-systems", "local-se-database-systems"] }),
  course({ key: "local-se-mobile-app-engineering", title: COURSE_TITLES["local-se-mobile-app-engineering"], shortDescription: "Mobile application architecture, platform constraints, offline behavior, device APIs, and UX considerations.", tags: ["mobile", "application engineering"], difficultyLevel: "Advanced", estimatedHours: 45, prerequisites: ["local-se-web-platform", "local-se-api-design"] }),
  course({ key: "local-se-cross-platform-mobile", title: COURSE_TITLES["local-se-cross-platform-mobile"], shortDescription: "Cross-platform mobile implementation, shared code, native bridges, navigation, state, and packaging.", tags: ["mobile", "cross-platform"], difficultyLevel: "Advanced", estimatedHours: 40, prerequisites: ["local-se-mobile-app-engineering"] }),
  course({ key: "local-se-mobile-quality-release", title: COURSE_TITLES["local-se-mobile-quality-release"], shortDescription: "Mobile testing, accessibility, performance, store release, analytics, crash reporting, and update strategy.", tags: ["mobile", "quality"], difficultyLevel: "Advanced", estimatedHours: 35, prerequisites: ["local-se-mobile-app-engineering", "local-se-testing-quality"] }),
  course({ key: "local-se-data-engineering", title: COURSE_TITLES["local-se-data-engineering"], shortDescription: "Batch data pipelines, modeling, orchestration, storage, quality checks, and production data movement.", tags: ["data engineering", "pipelines"], difficultyLevel: "Advanced", estimatedHours: 45, prerequisites: ["local-se-sql-data-modeling"] }),
  course({ key: "local-se-analytics-engineering", title: COURSE_TITLES["local-se-analytics-engineering"], shortDescription: "Analytics models, metrics layers, transformations, testing, lineage, and decision-support data products.", tags: ["analytics", "data"], difficultyLevel: "Advanced", estimatedHours: 40, prerequisites: ["local-se-data-engineering"] }),
  course({ key: "local-se-stream-processing", title: COURSE_TITLES["local-se-stream-processing"], shortDescription: "Streaming architecture, event-time processing, windowing, delivery guarantees, and operational tradeoffs.", tags: ["streaming", "data engineering"], difficultyLevel: "Advanced", estimatedHours: 40, prerequisites: ["local-se-data-engineering", "local-se-event-driven-architecture"] }),
  course({ key: "local-se-capstone-i", title: COURSE_TITLES["local-se-capstone-i"], shortDescription: "Plan, scope, architect, prototype, and review a substantial software engineering capstone project.", tags: ["capstone", "portfolio"], difficultyLevel: "Advanced", estimatedHours: 60, prerequisites: ["local-se-software-architecture", "local-se-testing-quality", "local-se-ci-cd-release"] }),
  course({ key: "local-se-capstone-ii", title: COURSE_TITLES["local-se-capstone-ii"], shortDescription: "Implement, harden, document, deploy, and present a substantial software engineering capstone project.", tags: ["capstone", "portfolio"], difficultyLevel: "Advanced", estimatedHours: 60, prerequisites: ["local-se-capstone-i"] }),
  course({ key: "local-se-portfolio-career", title: COURSE_TITLES["local-se-portfolio-career"], shortDescription: "Portfolio polish, resume narrative, interview preparation, project presentation, and readiness review.", tags: ["career", "portfolio"], difficultyLevel: "Advanced", estimatedHours: 30, prerequisites: ["local-se-capstone-ii"] }),
];

export const softwareEngineeringCourseWrapperIds = softwareEngineeringCourseWrappers.map((course) => course.key);

export default softwareEngineeringCourseWrappers;
