export type CourseTaxonomyItem = {
  id: string;
  label: string;
  departments?: CourseTaxonomyItem[];
};

export const courseCategories: CourseTaxonomyItem[] = [
  {
    id: "arts-humanities",
    label: "College of Arts and Humanities",
    departments: [
      { id: "english", label: "English" },
      { id: "history", label: "History" },
      { id: "philosophy", label: "Philosophy" },
      { id: "world-languages", label: "World Languages and Literatures" },
      { id: "religious-studies", label: "Religious Studies" },
      { id: "classics", label: "Classics" },
      { id: "comparative-literature", label: "Comparative Literature" },
      { id: "writing-rhetoric", label: "Writing and Rhetoric" },
    ],
  },
  {
    id: "fine-performing-arts",
    label: "College of Fine and Performing Arts",
    departments: [
      { id: "art-design", label: "Art and Design" },
      { id: "art-history", label: "Art History" },
      { id: "music", label: "Music" },
      { id: "theatre", label: "Theatre" },
      { id: "dance", label: "Dance" },
      { id: "film-media-arts", label: "Film and Media Arts" },
      { id: "creative-writing", label: "Creative Writing" },
    ],
  },
  {
    id: "business-management",
    label: "College of Business and Management",
    departments: [
      { id: "accounting", label: "Accounting" },
      { id: "finance", label: "Finance" },
      { id: "marketing", label: "Marketing" },
      { id: "management", label: "Management" },
      { id: "economics", label: "Economics" },
      { id: "business-analytics", label: "Business Analytics" },
      { id: "information-systems", label: "Information Systems" },
      { id: "supply-chain-management", label: "Supply Chain Management" },
      { id: "entrepreneurship", label: "Entrepreneurship" },
      { id: "hospitality-management", label: "Hospitality Management" },
    ],
  },
  {
    id: "education",
    label: "College of Education",
    departments: [
      { id: "curriculum-instruction", label: "Curriculum and Instruction" },
      { id: "educational-leadership", label: "Educational Leadership" },
      { id: "special-education", label: "Special Education" },
      { id: "teacher-education", label: "Teacher Education" },
      { id: "educational-psychology", label: "Educational Psychology" },
      { id: "instructional-technology", label: "Instructional Technology" },
      { id: "counseling-human-development", label: "Counseling and Human Development" },
    ],
  },
  {
    id: "computing-information-sciences",
    label: "College of Computing and Information Sciences",
    departments: [
      { id: "computer-science", label: "Computer Science" },
      { id: "software-engineering", label: "Software Engineering" },
      { id: "information-science", label: "Information Science" },
      { id: "information-technology", label: "Information Technology" },
      { id: "cybersecurity", label: "Cybersecurity" },
      { id: "data-science", label: "Data Science" },
      { id: "artificial-intelligence", label: "Artificial Intelligence" },
      { id: "human-computer-interaction", label: "Human-Computer Interaction" },
      { id: "computer-engineering", label: "Computer Engineering" },
      { id: "electrical-engineering", label: "Electrical Engineering" },
      { id: "mechanical-engineering", label: "Mechanical Engineering" },
      { id: "civil-engineering", label: "Civil Engineering" },
      { id: "chemical-engineering", label: "Chemical Engineering" },
      { id: "biomedical-engineering", label: "Biomedical Engineering" },
      { id: "industrial-engineering", label: "Industrial and Systems Engineering" },
    ],
  },
  {
    id: "natural-sciences-mathematics",
    label: "College of Natural Sciences and Mathematics",
    departments: [
      { id: "mathematics", label: "Mathematics" },
      { id: "statistics", label: "Statistics" },
      { id: "physics", label: "Physics" },
      { id: "chemistry", label: "Chemistry" },
      { id: "biology", label: "Biology" },
      { id: "earth-sciences", label: "Earth Sciences" },
      { id: "environmental-science", label: "Environmental Science" },
      { id: "astronomy", label: "Astronomy" },
      { id: "neuroscience", label: "Neuroscience" },
    ],
  },
  {
    id: "social-sciences",
    label: "College of Social Sciences",
    departments: [
      { id: "anthropology", label: "Anthropology" },
      { id: "criminology", label: "Criminology" },
      { id: "geography", label: "Geography" },
      { id: "political-science", label: "Political Science" },
      { id: "psychology", label: "Psychology" },
      { id: "sociology", label: "Sociology" },
      { id: "urban-studies", label: "Urban Studies" },
      { id: "international-studies", label: "International Studies" },
    ],
  },
  {
    id: "health-sciences",
    label: "College of Health Sciences",
    departments: [
      { id: "kinesiology", label: "Kinesiology" },
      { id: "nutrition", label: "Nutrition" },
      { id: "occupational-therapy", label: "Occupational Therapy" },
      { id: "physical-therapy", label: "Physical Therapy" },
      { id: "speech-language-pathology", label: "Speech-Language Pathology" },
      { id: "health-administration", label: "Health Administration" },
      { id: "clinical-laboratory-science", label: "Clinical Laboratory Science" },
    ],
  },
  {
    id: "medicine",
    label: "School of Medicine",
    departments: [
      { id: "anesthesiology", label: "Anesthesiology" },
      { id: "family-medicine", label: "Family Medicine" },
      { id: "internal-medicine", label: "Internal Medicine" },
      { id: "neurology", label: "Neurology" },
      { id: "obstetrics-gynecology", label: "Obstetrics and Gynecology" },
      { id: "pathology", label: "Pathology" },
      { id: "pediatrics", label: "Pediatrics" },
      { id: "psychiatry", label: "Psychiatry" },
      { id: "radiology", label: "Radiology" },
      { id: "surgery", label: "Surgery" },
    ],
  },
  {
    id: "nursing",
    label: "School of Nursing",
    departments: [
      { id: "adult-gerontology-nursing", label: "Adult-Gerontology Nursing" },
      { id: "community-health-nursing", label: "Community Health Nursing" },
      { id: "family-nurse-practitioner", label: "Family Nurse Practitioner" },
      { id: "nursing-leadership", label: "Nursing Leadership" },
      { id: "pediatric-nursing", label: "Pediatric Nursing" },
      { id: "psychiatric-mental-health-nursing", label: "Psychiatric-Mental Health Nursing" },
    ],
  },
  {
    id: "public-health",
    label: "School of Public Health",
    departments: [
      { id: "biostatistics", label: "Biostatistics" },
      { id: "environmental-health", label: "Environmental Health" },
      { id: "epidemiology", label: "Epidemiology" },
      { id: "global-health", label: "Global Health" },
      { id: "health-policy-management", label: "Health Policy and Management" },
      { id: "community-health-sciences", label: "Community Health Sciences" },
    ],
  },
  {
    id: "law",
    label: "School of Law",
    departments: [
      { id: "business-law", label: "Business Law" },
      { id: "constitutional-law", label: "Constitutional Law" },
      { id: "criminal-law", label: "Criminal Law" },
      { id: "environmental-law", label: "Environmental Law" },
      { id: "health-law", label: "Health Law" },
      { id: "intellectual-property-law", label: "Intellectual Property Law" },
      { id: "international-law", label: "International Law" },
      { id: "public-interest-law", label: "Public Interest Law" },
    ],
  },
  {
    id: "agriculture-environmental-sciences",
    label: "College of Agriculture and Environmental Sciences",
    departments: [
      { id: "agricultural-economics", label: "Agricultural Economics" },
      { id: "animal-science", label: "Animal Science" },
      { id: "crop-soil-sciences", label: "Crop and Soil Sciences" },
      { id: "environmental-sciences", label: "Environmental Sciences" },
      { id: "food-science", label: "Food Science" },
      { id: "forestry-natural-resources", label: "Forestry and Natural Resources" },
      { id: "horticulture", label: "Horticulture" },
      { id: "plant-pathology", label: "Plant Pathology" },
    ],
  },
  {
    id: "architecture-planning-design",
    label: "College of Architecture, Planning, and Design",
    departments: [
      { id: "architecture", label: "Architecture" },
      { id: "interior-architecture", label: "Interior Architecture" },
      { id: "landscape-architecture", label: "Landscape Architecture" },
      { id: "urban-regional-planning", label: "Urban and Regional Planning" },
      { id: "industrial-design", label: "Industrial Design" },
      { id: "real-estate-development", label: "Real Estate Development" },
    ],
  },
  {
    id: "communication-media",
    label: "College of Communication and Media",
    departments: [
      { id: "advertising-public-relations", label: "Advertising and Public Relations" },
      { id: "communication-studies", label: "Communication Studies" },
      { id: "journalism", label: "Journalism" },
      { id: "media-production", label: "Media Production" },
      { id: "media-studies", label: "Media Studies" },
      { id: "strategic-communication", label: "Strategic Communication" },
    ],
  },
  {
    id: "public-policy-government",
    label: "School of Public Policy and Government",
    departments: [
      { id: "public-administration", label: "Public Administration" },
      { id: "public-policy", label: "Public Policy" },
      { id: "government", label: "Government" },
      { id: "international-affairs", label: "International Affairs" },
      { id: "nonprofit-management", label: "Nonprofit Management" },
      { id: "security-studies", label: "Security Studies" },
    ],
  },
  {
    id: "social-work-human-services",
    label: "School of Social Work and Human Services",
    departments: [
      { id: "social-work", label: "Social Work" },
      { id: "human-services", label: "Human Services" },
      { id: "community-practice", label: "Community Practice" },
      { id: "child-family-services", label: "Child and Family Services" },
      { id: "gerontology", label: "Gerontology" },
    ],
  },
  {
    id: "continuing-professional-studies",
    label: "School of Continuing and Professional Studies",
    departments: [
      { id: "professional-studies", label: "Professional Studies" },
      { id: "continuing-education", label: "Continuing Education" },
      { id: "workforce-development", label: "Workforce Development" },
      { id: "project-management", label: "Project Management" },
      { id: "organizational-leadership", label: "Organizational Leadership" },
    ],
  },
  {
    id: "interdisciplinary-studies",
    label: "College of Interdisciplinary Studies",
    departments: [
      { id: "interdisciplinary-studies", label: "Interdisciplinary Studies" },
      { id: "liberal-studies", label: "Liberal Studies" },
      { id: "gender-studies", label: "Gender Studies" },
      { id: "data-society", label: "Data and Society" },
      { id: "science-technology-society", label: "Science, Technology, and Society" },
      { id: "sustainability-studies", label: "Sustainability Studies" },
    ],
  },
];

export const courseTags: CourseTaxonomyItem[] = [
  { id: "writing", label: "Writing" },
  { id: "rhetoric", label: "Rhetoric" },
  { id: "literature", label: "Literature" },
  { id: "philosophy", label: "Philosophy" },
  { id: "history", label: "History" },
  { id: "ethics", label: "Ethics" },
  { id: "visual-arts", label: "Visual arts" },
  { id: "music", label: "Music" },
  { id: "theater", label: "Theater" },
  { id: "mathematics", label: "Mathematics" },
  { id: "statistics", label: "Statistics" },
  { id: "physics", label: "Physics" },
  { id: "chemistry", label: "Chemistry" },
  { id: "biology", label: "Biology" },
  { id: "earth-science", label: "Earth science" },
  { id: "environmental-science", label: "Environmental science" },
  { id: "computer-science", label: "Computer science" },
  { id: "programming", label: "Programming" },
  { id: "python", label: "Python" },
  { id: "software-engineering", label: "Software engineering" },
  { id: "software-architecture", label: "Software architecture" },
  { id: "web-development", label: "Web development" },
  { id: "accessibility", label: "Accessibility" },
  { id: "apis", label: "APIs" },
  { id: "data-science", label: "Data science" },
  { id: "artificial-intelligence", label: "Artificial intelligence" },
  { id: "machine-learning", label: "Machine learning" },
  { id: "mlops", label: "MLOps" },
  { id: "systems", label: "Systems" },
  { id: "cybersecurity", label: "Cybersecurity" },
  { id: "information-systems", label: "Information systems" },
  { id: "electrical-engineering", label: "Electrical engineering" },
  { id: "mechanical-engineering", label: "Mechanical engineering" },
  { id: "civil-engineering", label: "Civil engineering" },
  { id: "biomedical-engineering", label: "Biomedical engineering" },
  { id: "accounting", label: "Accounting" },
  { id: "finance", label: "Finance" },
  { id: "marketing", label: "Marketing" },
  { id: "entrepreneurship", label: "Entrepreneurship" },
  { id: "economics", label: "Economics" },
  { id: "psychology", label: "Psychology" },
  { id: "sociology", label: "Sociology" },
  { id: "anthropology", label: "Anthropology" },
  { id: "political-science", label: "Political science" },
  { id: "public-policy", label: "Public policy" },
  { id: "law", label: "Law" },
  { id: "education", label: "Education" },
  { id: "instructional-design", label: "Instructional design" },
  { id: "medicine", label: "Medicine" },
  { id: "nursing", label: "Nursing" },
  { id: "public-health", label: "Public health" },
  { id: "anatomy", label: "Anatomy" },
  { id: "architecture", label: "Architecture" },
  { id: "design", label: "Design" },
  { id: "documentation", label: "Documentation" },
  { id: "media-studies", label: "Media studies" },
  { id: "journalism", label: "Journalism" },
  { id: "agriculture", label: "Agriculture" },
];

const categoryLabels = new Map(courseCategories.map((category) => [category.id, category.label]));
const categoryDepartments = new Map(courseCategories.map((category) => [category.id, category.departments ?? []]));
const tagLabels = new Map(courseTags.map((tag) => [tag.id, tag.label]));

export function getCourseCategoryLabel(categoryId?: string) {
  return categoryId ? categoryLabels.get(categoryId) ?? categoryId : "Not categorized";
}

export function getCourseTagLabels(tagIds?: string[]) {
  return (tagIds ?? []).map((tagId) => tagLabels.get(tagId) ?? tagId);
}

export function getCourseCategoryDepartments(categoryId?: string) {
  return categoryId ? categoryDepartments.get(categoryId) ?? [] : [];
}
